### ISSUE TITLE
voxel rcnn usage

### ISSUE THREAD

**Issue by vehxianfish** [dvlab-research/FocalsConv#12]
Hi, thanks for your excellent work! I want to check the eval result of 3 classes on voxel rcnn. So how can I train?
In the kitti_model directory, I can't see voxel rcnn with focal conv configuration files of 3 classes.
Can you release it? thanks again

**Comment by yukang2017** [comment]
Hi, thanks for your interests in our work.

Because Voxel R-CNN is officially designed for single class, we did not test it on three classes before. 
However, it is not a hard job to modify it to be multi-class. I have just uploaded the config file that supports 3 classes. You can found it here. 

[voxel_rcnn_multiclasses_focalsconv.yaml](https://github.com/dvlab-research/FocalsConv/blob/master/OpenPCDet/tools/cfgs/kitti_models/voxel_rcnn_multiclasses_focalsconv.yaml)

**Comment by vehxianfish** [comment]
Thank you for your prompt response!

**Comment by yukang2017** [comment]
It 's all right. I will currently close this issue. Please feel free to reopen it. If there are any performance issue regarding to this config file.

**Comment by vehxianfish** [comment]
> Hi, thanks for your interests in our work.
> 
> Because Voxel R-CNN is officially designed for single class, we did not test it on three classes before. However, it is not a hard job to modify it to be multi-class. I have just uploaded the config file that supports 3 classes. You can found it here.
> 
> [voxel_rcnn_multiclasses_focalsconv.yaml](https://github.com/dvlab-research/FocalsConv/blob/master/OpenPCDet/tools/cfgs/kitti_models/voxel_rcnn_multiclasses_focalsconv.yaml)

Hi, can you provide a yaml file fo voxel CNN but not multi-model?

**Comment by yukang2017** [comment]
Sure. You can find it here, [voxel_rcnn_multiclasses_focalsconv_lidar.yaml](https://github.com/dvlab-research/FocalsConv/blob/master/OpenPCDet/tools/cfgs/kitti_models/voxel_rcnn_multiclasses_focalsconv_lidar.yaml).
