### ISSUE TITLE
Issues about fusing multimodal features

### ISSUE THREAD

**Issue by Eaton2022** [dvlab-research/FocalsConv#18]
dear author:
        In def construct_multimodal_features, there are two ways to fuse multimodal features. Fuse_sum = False means we use concatenation. But when I set fuse_sum = False in   "out = out.replace_feature(self.construct_multimodal_features(out, x_rgb, batch_dict, False))", code will report an error which is  "RuntimeError: running_mean should contain 32 elements not 16". I wonder how to amend code to solve this problem.  Thanks a lot!

**Comment by yukang2017** [comment]
Hi,

This is because the concatenation will enlarge the output channels. I think there are two channel numbers needed to be changed

(1) The input channel of BN

planes should be 2 * planes, in the following line.
https://github.com/dvlab-research/FocalsConv/blob/494f9f43b8506ad7d4c21bb062f8fef8ee89c4b0/CenterPoint/det3d/models/backbones/focal_sparse_conv/focal_sparse_conv.py#L18

(2) The input channel of the next stage 

the input channel 16 should be 32, in the following line.
https://github.com/dvlab-research/FocalsConv/blob/494f9f43b8506ad7d4c21bb062f8fef8ee89c4b0/CenterPoint/det3d/models/backbones/scn_focal.py#L155


Please feel free to reply if there are still any other issues.

**Comment by Eaton2022** [comment]
dear author:
           thanks for your reply, I amend code as you advice in voxel-rcnn-focal-multi, but got wrong imformation:"RuntimeError: running_mean should contain 16 elements not 32". It seems we should not only amend two places. Could you please pass test by yourself in voxel-rcnn-focal-multi and kindly reply? Thanks a lot!

**Comment by yukang2017** [comment]
Sorry. I thought that you were talking about the Centerpoint model.

I just updated this file
https://github.com/dvlab-research/FocalsConv/blob/master/OpenPCDet/pcdet/models/backbones_3d/focal_sparse_conv/focal_sparse_conv.py

You can then add `fuse_sum=False` in
https://github.com/dvlab-research/FocalsConv/blob/4105ebab354354f1ad3259e781c932957552e336/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone_focal.py#L148

And set the input channel here to be 32 instead of 16
https://github.com/dvlab-research/FocalsConv/blob/4105ebab354354f1ad3259e781c932957552e336/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone_focal.py#L162

I have just tested it.

**Comment by Eaton2022** [comment]
thanks for your kind help!

**Comment by yukang2017** [comment]
Thanks for your interest in our work. Please feel free to reopen this issue or open other issues if there are still any problems.
