### ISSUE TITLE
OpenPCDet, spconv version issue

### ISSUE THREAD

**Issue by Minwookk** [dvlab-research/FocalsConv#3]
In instruction, you recommended spconv 2.x version .
but, given checkpoint trained pcdet version ==0.3.0.
Which one is correct?

**Comment by yukang2017** [comment]
Hi, spconv 2.x is correct. We can also use spconv 2.x in pcdet==0.3.0 version.

**Comment by Minwookk** [comment]
In OpenPCDet official github,
pcdet version ==0.3.0 should be matched to spconv 1.x version. 
do you ignore it? and your github provides pcdet version 0.5.2, isn't it?

**Comment by yukang2017** [comment]
There is not so much difference in usage between spconv 2.x and spconv 1.x. 
Because spconv 2.x is easy to install, I change the version of spconv to 2.x in pcdet==0.3.0 when preparing the checkpoints, following this [doc](https://github.com/traveller59/spconv/blob/master/docs/SPCONV_2_BREAKING_CHANGEs.md).
