### ISSUE TITLE
Data augmentation in Section 3.3. 

### ISSUE THREAD

**Issue by Chuanbo-Yu** [dvlab-research/FocalsConv#4]
It's an interesting work. I have a question about the words in section 3.3 of the paper "For ground-truth sampling, we copy the corresponding 2D objects onto images. Rather than using an additional segmentation model or mask annotations [57], we directly crop objects in bounding boxes for simplification." However,  copying other objects to the current scene will overlap in the RGB image. Copying paste objects from other scenes in point clouds is effective and overlapping objects can be removed through collision experiments. How to deal with overlapping objects in RGB images?

**Comment by yukang2017** [comment]
Hi, thanks for your interests in our work. 

It is true that this operation will cause overlap in the RGB image. We did not solve this problem and just leave it here, because it has little relation to our main motivation. And the results still perform well even if with this issue remain. 

Below is a illustration of the a RGB training image.
![image](https://user-images.githubusercontent.com/24690867/168419982-dedee243-d77a-4f3f-94f1-310aa7fbc9b5.png)

I think there might be some other well-design method that is specific to this copy-pasting issue. [This paper](https://openaccess.thecvf.com/content/CVPR2021/papers/Wang_PointAugmenting_Cross-Modal_Augmentation_for_3D_Object_Detection_CVPR_2021_paper.pdf) might be a solution.
